### ISSUE TITLE
[IDEA] How about creating a team for the development?

### ISSUE THREAD

**Issue by nks15** [ChoiWooYoung/Melodic_KERNEL#1]
Same as above. I think it's also nice to have a solid team just for kernel developing, such as Melodic Team, etc.

ㅋㅋㅋㅋㅋ
오랜만입니다.

**Comment by ChoiWooYoung** [comment]
Of couse, Why not? :) However I dont have much time to build kernels because of school work, but I could build them when i have free time :p
ㅋㅋㅋㅋㅋㅋ 진짜 오래간만입니다.
디벨에서는 작년이래로 안보이시던데 잘지내고 계시지요? 요즘은 빌드할시간이 마땅치않아서 빌드는 못하고있습니다 ㅋㅋ 뭐 수정하는것도 다른 기기 커밋만 보면서 따라하는지라ㅋㅋ
현재는 중국 기기 사용중인데 소스는 깃허브에 널렸으나 롬들은 희박해서 한번 RR, LOS빌드해보려합니다. 하하 시간 있으시다면 커널 개발하는 소규모 팀 만드는것도 참괜찮은 생각입니다 xD
 
//커널소스 1년만에 올리는겊실화입니까 ㅋㅋ 윈도우 환경에서 올리려니 URLF오류 계속떠서 좀 골때리네요 ㅋㅋ

**Comment by nks15** [comment]
OK then. By the way, I'm also busy because of my school work. LOL :)

역시 학교 때문이죠 뭐. 내신이 워낙 커서 디벨은 물론 이쪽은 요즘 거의 잊고 삽니다 ㅋㅋ. 나중에 시간이란 게 있다면 들려야죠.

// Bash for Windows (WSL) 기능 사용해보셨나요? 그것도 아님 깃허브 데스크톱 있던데...

**Comment by ChoiWooYoung** [comment]
LOLOL :D http://dic.impact.pe.kr/ecmaster-cgi/search.cgi?kwd=%C7%F6%BD%C7%C0%FB%C0%B8%B7%CE
현실적으로 - 국내최대의 영어사전, 전문용어, 의학 용어도 OK
http://dic.impact.pe.kr/ecmaster-cgi/search.cgi?kwd=%C7%F6%BD%C7%C0%FB%C0%B8%B7%CE
현실적으로 - 국내최대의 영어사전, 전문용어, 의학 용어도 OK
In reality, Typical Korean Students do not have time, Really.

깃허즈 데스크탖은 진행이 되는건지 안되능건지 잘모르겟어서 ㅠㅠ
WSL는 업로드가 되지않은 소스를 gui없이 어떻게 받아올지 막막해서 윈도우 장치에서 바로 업로드가능한 git-scm 사용했습니다. 누락된 파일도 있을것 같아요 ㅠㅠ
LD, CRLF 오류 넘나 짜증나는것 ㅜㅜ
//요즘은 뭐하고 사시나요?

**Comment by ChoiWooYoung** [comment]
커밋추가도 너무 재밌는것 :dancer:

**Comment by nks15** [comment]
import student as s

while s.is_alive():
    if s.task != s.STUDYING:
        s.study(length=infinite)

// 위 코드처럼 삽니다... (커밋 재미있죠!)

**Comment by nks15** [comment]
Hahaha. Again, thanks for your time.

And let's use Telegram from now on. It's a fast way to contact each other.
